---
- name: Add apt repositories.
  apt_repository:
    repo: "deb {{ item }}"
    state: present
  with_items:
    - 'http://download.webmin.com/download/repository sarge contrib'
    - 'http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib'

- name: Install webmin.
  sudo: yes
  apt:
    name: "webmin={{ webmin_version }}"
    state: present
    force: yes
