---
- name: Install the RPM (CentOS).
  yum: >
    name="http://www.webmin.com/download/rpm/webmin-current.rpm"
    state=present
  sudo: yes
  when: ansible_os_family == 'RedHat'

- name: Install webmin (CentOS).
  yum: name=webmin state=present
  sudo: yes
  when: ansible_os_family == 'RedHat'

- name: Start the webmin service.
  service: name=webmin state=started enabled=yes
