---
- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: ubuntu.yml
  when: ansible_os_family == 'Ubuntu'

- name: Start the webmin service.
  service:
    name: webmin
    state: started
    enabled: yes
